# Single monitor setup
# monitor=,preferred,auto,auto

# Dual monitor setup
# Gaming Setup for more performance
# monitor = HDMI-A-1, 1366x768@60.00, 0x0, 1
# monitor = HDMI-A-1, preferred, 0x0, auto
# monitor = eDP-1, preferred, 1366x0, 1

# Daily drive setup
monitor = HDMI-A-1, 1920x1080@60.00, 0x0, 1
monitor = eDP-1, 1920x1080@60.00, 1920x0, 1

