# windowrule = float on, match:class ^(kitty)$ on
# windowrule = float on, match:class ^(pavucontrol|blueman-manager)$ on
windowrule = float on, match:class ^(blueman-manager)$ on
windowrule = float on, match:class ^(org.pulseaudio.pavucontrol)$ on

windowrule = workspace special, match:class obsidian
windowrule = opacity 0.8 0.8, match:class ^(obsidian)$

windowrule = workspace 6, match:class spotify
windowrule = workspace 8, match:class steam

windowrule = tile on, match:class ^(steam)$

windowrule = match:class ^(code)$, opacity 0.88 override 0.5 override
windowrule = no_blur on, match:class ^(code)$

# windowrule = float on, match:class ^(kitty)$, match:title ^(kitty)$
windowrule = animation popin, no_anim on, match:class ^(wofi)$

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}
